###############################################################################
# Name: 01-tidy-library.R                                                     #
# Description: Examine and clean LibraryThing contents                        #
###############################################################################

# Housekeeping ----------------------------------------------------------------

library(dplyr)
library(janitor)

# Tidy data -------------------------------------------------------------------

"
Import TSV from LibraryThing https://www.librarything.com/more
"

lib <- read.delim("./data/librarything_Keiras_lip_balm.tsv")

glimpse(lib, width = 80)

# Rows: 363
# Columns: 49
# $ Book.Id                <int> 178392265, 178392270, 178392285, 178392290, 178…
# $ Title                  <chr> "The Ultimate Hitchhiker's Guide to the Galaxy"…
# $ Sort.Character         <int> 5, 1, 1, 1, 5, 1, 5, 1, 1, 1, 5, 5, 1, 1, 5, 1,…
# $ Primary.Author         <chr> "Adams, Douglas", "Arendt, Hannah", "Auden, W. …
# $ Primary.Author.Role    <chr> "Author", "Author", "Author", "Author", "Author…
# $ Secondary.Author       <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Secondary.Author.Roles <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Publication            <chr> "Del Rey (2002), 832 pages", "Penguin Classics …
# $ Date                   <chr> "2002", "2006", "1995", "2009", "2007", "2003",…
# $ Review                 <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Rating                 <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Comment                <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Private.Comment        <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Summary                <chr> "The Ultimate Hitchhiker's Guide to the Galaxy …
# $ Media                  <chr> "Paperback", "Paperback", "Hardcover", "Paperba…
# $ Physical.Description   <chr> "832 p.; 6.1 inches", "336 p.; 5.13 x 0.56 inch…
# $ Weight                 <chr> "1.7 pounds", "0.06 pounds", "0.5 pounds", "0.5…
# $ Height                 <chr> "6.1 inches", "0.56 inches", "4.39 inches", "7.…
# $ Thickness              <chr> "9.2 inches", "7.71 inches", "6.48 inches", "4 …
# $ Length                 <chr> "1.4 inches", "5.13 inches", "0.74 inches", "0.…
# $ Dimensions             <chr> "6.1 x 1.4 x 9.2 inches", "0.56 x 5.13 x 7.71 i…
# $ Page.Count             <dbl> 832, 336, 256, 311, 739, 368, 224, 314, 493, 36…
# $ LCCN                   <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Acquired               <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Date.Started           <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Date.Read              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Barcode                <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ BCID                   <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Tags                   <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Collections            <chr> "Your library", "Your library", "Your library",…
# $ Languages              <chr> "English", "English", "English", "English", "En…
# $ Original.Languages     <chr> "English", "English", "English", "English", "En…
# $ LC.Classification      <chr> "PR6051.D3352", "DD247.E5", "PR6001.U4", "BR65.…
# $ ISBN                   <chr> "[0345453743]", "[9780143039884]", "[0679443673…
# $ ISBNs                  <chr> "0345453743, 9780345453747", "9780143039884, 01…
# $ Subjects               <chr> "", "Eichmann, Adolf, 1906-1962|Holocaust, Jewi…
# $ Dewey.Decimal          <dbl> 823.9140, 940.5318, 821.9120, 270.2092, 823.700…
# $ Dewey.Wording          <chr> "1901-1999 > 1945-1999 > English fiction > Engl…
# $ Other.Call.Number      <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Copies                 <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
# $ Source                 <chr> "amazon.com all media", "amazon.com books", "am…
# $ Entry.Date             <chr> "[2020-02-01]", "[2020-02-01]", "[2020-02-01]",…
# $ From.Where             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ OCLC                   <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Work.id                <int> 9440376, 3485, 23324, 9036, 6815042, 2228, 1698…
# $ Lending.Patron         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Lending.Status         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Lending.Start          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
# $ Lending.End            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…

lib <- clean_names(lib)

sim <- stringdist::stringdistmatrix(lib$primary_author, lib$primary_author)

sim <- which(sim < 5 & sim > 0, arr.ind = TRUE)

