library(RSelenium)

rD <- rsDriver(browser = "chrome", port = 2222L, chromever = "107.0.5304.62")
remDr <- rD[["client"]]
remDr$navigate("https://www.librarything.com/catalog/Keiras_lip_balm")

html <- remDr$getPageSource()[[1]]

https://www.librarything.com/catalog/Keiras_lip_balm

<html><head>\n<title>Keiras_lip_balm's books | LibraryThing</title>\n\n<meta name=\"keywords\" content=\"librarything, library, thing, catalog your books, catalogue your books, book cataloging, library, free book catalog, catalogue\">\n<meta name=\"version\" content=\"\">\n<meta name=\"apple-itunes-app\" content=\"app-id=948824489\">\n<meta name=\"description\" content=\"LibraryThing is a cataloging and social networking site for booklovers\">\n<meta name=\"language\" content=\"en\">\n\n<link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\"><script src=\"https://image.librarything.com/js/jquery-1.8.0.min.js?v=2\" type=\"text/javascript\" flag_fte=\"1\" language=\"Javascript\" style=\"color: rgb(0, 0, 0);\"></script>\n<script src=\"https://www.librarything.com/js2/mmlog.js?4837\" flag_fte=\"2\" static_host=\"https://www.librarything.com/\" type=\"text/javascript\" language=\"Javascript\"></script>\n<script src=\"https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js\" type=\"text/javascript\" flag_fte=\"1\" language=\"Javascript\"></script>\n<script src=\"https://www.librarything.com/js/lt_utility.js?4837\" flag_fte=\"2\" static_host=\"https://www.librarything.com/\" type=\"text/javascript\" language=\"Javascript\"></script>\n<script src=\"https://www.librarything.com/js2/basics1.js?4837\" flag_fte=\"2\" static_host=\"https://www.librarything.com/\" type=\"text/javascript\" language=\"Javascript\"></script>\n<script src=\"https://www.librarything.com/js2/hack_base_2013_1.js?4837\" flag_fte=\"2\" static_host=\"https://www.librarything.com/\" type=\"text/javascript\" language=\"Javascript\"></script>\n\n <script type=\"text/javascript\">if (window.jQuery && (typeof $J == 'undefined')) { $J = jQuery.noConflict();} </script></head><frameset rows=\"86, 100%\" border=\"0\" style=\"margin:0px;padding:0px;\">\n<frame name=\"top\" src=\"/catalog_top.php?view=Keiras_lip_balm\" scrolling=\"no\" frameborder=\"0\" noresize=\"\"><frame name=\"bottom\" src=\"/catalog_bottom.php?view=Keiras_lip_balm\" scrolling=\"yes\" frameborder=\"0\" noresize=\"\"></frameset>\n<noframes>\n<body>\n<p>LibraryThing (\"Catalog your books online\") requires frames.</p>\n</body>\n</noframes>\n\n\n\n</html>